import {BASE,calculate} from './nz-model.mjs';
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-NZ',{style:'currency',currency:'NZD',maximumFractionDigits:0}).format(n), dec=n=>n.toFixed(2);
let current;
const keys=['flow','filterMonths','tariff','discount','dayValue','unitPrice','setup','staff'];
function read(){const v={...BASE};for(const k of keys){const el=$(k);if(!el.checkValidity()||el.value.trim()==='')throw Error('Check '+el.parentElement.firstChild.textContent.trim()+'.');v[k]=Number(el.value);}const d=$('delivery');if(!d.checkValidity()||d.value.trim()==='')throw Error('Check realised CADR percentage.');const [cadr,watts]=$('speed').value.split(',').map(Number);return {...v,cadr:cadr*Number(d.value)/100,watts};}
function update(){try{const v=read(),r=calculate(v);current={v,r};$('error').hidden=true;$('results').hidden=false;$('export').disabled=false;
for(const [id,value] of Object.entries({annual:money(r.annual),perPupil:money(r.perPupil),pv:money(r.pv),threshold:r.breakEvenDays===null?'No finite threshold':r.breakEvenDays.toFixed(1),added:dec(r.addedACH),total:dec(r.totalACH)}))$(id).textContent=value;
$('thresholdSuffix').hidden=v.dayValue===0;
$('thresholdNote').textContent=v.dayValue>0?`At an assumed ${money(v.dayValue)} of non-overlapping resource value per avoided illness-related pupil absence day, sustained annually for five years.`:'With zero value assigned per day, avoided days alone cannot cover the cost.';
$('airNote').textContent=`${r.outdoor.toFixed(1)} m³/h of assumed outdoor air + ${r.added.toFixed(0)} m³/h of filtration. Outdoor ventilation alone: ${dec(r.outdoorACH)} ACH. CO₂ removal is unchanged by filtration.`;
const rows=[['Equipment plus setup','2 units + setup and commissioning, once',r.capital],['HEPA allowance','One two-pack per unit per replacement; annualised',v.units*v.hepa*12/v.filterMonths],['Carbon allowance','One two-pack per unit per replacement; annualised',v.units*v.carbon*12/v.filterMonths],['Electricity',`${r.powerKwh.toFixed(2)} kWh/year × $${v.tariff.toFixed(2)}/kWh`,r.energy],['Staff time','Annual resource allowance',v.staff],['Total operating allowance','Per year; excludes upfront equipment',r.operating]];
$('costRows').replaceChildren(...rows.map(row=>{const tr=document.createElement('tr');row.forEach((x,i)=>{const td=document.createElement('td');td.textContent=i===2?'$'+x.toFixed(2):x;tr.append(td)});return tr}));
}catch(e){current=null;$('results').hidden=true;$('costRows').replaceChildren();$('error').textContent=e.message;$('error').hidden=false;$('export').disabled=true;}}
$('inputs').addEventListener('input',update);$('inputs').addEventListener('change',update);$('inputs').addEventListener('submit',e=>e.preventDefault());$('reset-case').addEventListener('click',()=>{$('inputs').reset();update()});
$('export').addEventListener('click',()=>{if(!current)return;const blob=new Blob([JSON.stringify({case:'NZ older classroom policy archetype',version:'2026-09-13-v1',currency:'NZD',priceBasis:'September 2026 listed prices and allowances; GST inclusion unverified; no GST adjustment',clinicalBenefits:'unestimated',deliveryPercent:Number($('delivery').value),speed:$('speed').value,inputs:current.v,results:current.r},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nz-classroom-policy-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
const scenarios=[['Central case',{}],['8% discount rate',{discount:8}],['Filters every 6 months',{filterMonths:6}],['Filters every 24 months',{filterMonths:24}],['Electricity $0.20/kWh',{tariff:.20}],['Electricity $0.40/kWh',{tariff:.40}],['Maximum speed and power',{cadr:508,watts:60}],['Setup and staff allowances doubled',{setup:300,staff:120}]];
$('sensitivity').replaceChildren(...scenarios.map(([label,patch])=>{const r=calculate({...BASE,...patch}),tr=document.createElement('tr');[label,money(r.annual),r.breakEvenDays.toFixed(2)].forEach(x=>{const td=document.createElement('td');td.textContent=x;tr.append(td)});return tr}));
fetch('./sources.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(sources=>{$('sourceList').replaceChildren(...sources.map(s=>{const li=document.createElement('li'),a=document.createElement('a');a.href=s.url;a.textContent=`[${s.id}] ${s.title}`;li.append(a,document.createTextNode('. '+s.supports));return li}))}).catch(()=>{$('sourceList').textContent='Source list could not load. Open sources.json alongside this page.'});
update();
